name: Create Auth File

on: 
  push:
    branches:
      - main

jobs:
  create-auth-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create auth.txt from GitHub Secrets
        run: |
          echo "AUTH_USERNAME Length: ${#AUTH_USERNAME}"
          echo "AUTH_PASSWORD Length: ${#AUTH_PASSWORD}"
          echo "${{ secrets.AUTH_USERNAME }}" > auth.txt
          echo "${{ secrets.AUTH_PASSWORD }}" >> auth.txt

      - name: Upload auth.txt as an artifact (Downloadable)
        uses: actions/upload-artifact@v4
        with:
          name: auth-file
          path: auth.txt
